# This file was auto-generated by Fern from our API Definition.

import typing

BackupScheduleItemDtoBackupMethod = typing.Union[typing.Literal["xtrabackup", "pg-basebackup", "datafile"], typing.Any]
