# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class BucketDto(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Name of the bucket.
    """

    tenant: str = pydantic.Field()
    """
    Tenant the bucket belongs to.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the bucket was created."),
    ]
    num_objects: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="numObjects"),
        pydantic.Field(alias="numObjects", description="Number of objects stored in the bucket."),
    ]
    size_kb: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="sizeKb"),
        pydantic.Field(alias="sizeKb", description="Total size of objects in the bucket, in kilobytes."),
    ]
    s3path: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="s3Path"),
        pydantic.Field(alias="s3Path", description="S3-compatible path to the bucket."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
