# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .create_vm_dto_subscription_period import CreateVmDtoSubscriptionPeriod
from .network_access_dto import NetworkAccessDto
from .vm_specs_dto import VmSpecsDto


class CreateVmDto(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    VM name
    """

    region: str = pydantic.Field()
    """
    Region label
    """

    vm_package: typing_extensions.Annotated[
        str, FieldMetadata(alias="vmPackage"), pydantic.Field(alias="vmPackage", description="VM package label")
    ]
    vm_specs: typing_extensions.Annotated[
        VmSpecsDto, FieldMetadata(alias="vmSpecs"), pydantic.Field(alias="vmSpecs", description="VM specifications")
    ]
    image: str = pydantic.Field()
    """
    Image label to use for the VM
    """

    network: str = pydantic.Field()
    """
    UUID of pre-existing customer network
    """

    subscription_period: typing_extensions.Annotated[
        CreateVmDtoSubscriptionPeriod,
        FieldMetadata(alias="subscriptionPeriod"),
        pydantic.Field(alias="subscriptionPeriod", description="Subscription period"),
    ]
    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of tags to add to the VM
    """

    keypairs: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Names of SSH key pairs to use (optional)
    """

    userdata: typing.Optional[str] = pydantic.Field(default=None)
    """
    Base64-encoded cloud-init userdata script (optional)
    """

    network_access: typing_extensions.Annotated[
        typing.Optional[NetworkAccessDto],
        FieldMetadata(alias="networkAccess"),
        pydantic.Field(
            alias="networkAccess",
            description="Optional network access configuration applied after the VM is created. Only honored when no `network` is provided (i.e. an isolated network is auto-created). Creates an egress allow-all rule (if requested) and adds port forwarding + firewall rules for the requested inbound ports against the network's public IP.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
