# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CreateVolumeDto(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    The name of the volume
    """

    size_gb: typing_extensions.Annotated[
        int, FieldMetadata(alias="sizeGb"), pydantic.Field(alias="sizeGb", description="The size of the volume in GB")
    ]
    region: str = pydantic.Field()
    """
    Label of the region where the volume will be created
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
