# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CreateClusterRestoreDto(UniversalBaseModel):
    source_cluster_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sourceClusterId"),
        pydantic.Field(alias="sourceClusterId", description="Identifier of the source cluster to restore from."),
    ]
    backup_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="backupName"),
        pydantic.Field(alias="backupName", description="Name of the backup to restore from on the source cluster."),
    ]
    restore_point_in_time: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="restorePointInTime"),
        pydantic.Field(
            alias="restorePointInTime",
            description="Point-in-time to restore to, in ISO 8601 format. Omit to restore to the backup timestamp.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
