# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .detailed_isolated_network_response_dto_status import DetailedIsolatedNetworkResponseDtoStatus


class DetailedIsolatedNetworkResponseDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the network
    """

    name: str = pydantic.Field()
    """
    Name of the network
    """

    description: str = pydantic.Field()
    """
    Description of the network
    """

    cidr: str = pydantic.Field()
    """
    CIDR of the network
    """

    gateway: str = pydantic.Field()
    """
    Gateway IP address
    """

    status: DetailedIsolatedNetworkResponseDtoStatus = pydantic.Field()
    """
    Network status
    """

    region: str = pydantic.Field()
    """
    Region where the network is located
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Network creation date"),
    ] = None
    type: str = pydantic.Field()
    """
    Network type
    """

    acl_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="aclType"),
        pydantic.Field(alias="aclType", description="Type of the ACL list"),
    ] = None
    ip_addresses: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="ipAddresses"),
        pydantic.Field(alias="ipAddresses", description="IP addresses associated with this network"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
