# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FirewallRuleResponseDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the firewall rule.
    """

    protocol: str = pydantic.Field()
    """
    Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`.
    """

    start_port: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="startPort"),
        pydantic.Field(alias="startPort", description="Start of the port range the rule applies to."),
    ] = None
    end_port: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="endPort"),
        pydantic.Field(alias="endPort", description="End of the port range the rule applies to."),
    ] = None
    ip_address_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="ipAddressId"),
        pydantic.Field(alias="ipAddressId", description="Identifier of the public IP the rule is attached to."),
    ]
    ip_address: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="ipAddress"),
        pydantic.Field(alias="ipAddress", description="Public IP address the rule is attached to."),
    ]
    state: str = pydantic.Field()
    """
    Current lifecycle state of the rule.
    """

    source_cidr_list: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sourceCidrList"),
        pydantic.Field(alias="sourceCidrList", description="Source CIDR allowed to reach the rule target."),
    ]
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Direction of traffic this rule applies to.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the rule was created."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
