# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class IsolatedNetworkConfigDto(UniversalBaseModel):
    network_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="networkId"),
        pydantic.Field(alias="networkId", description="Identifier of the isolated network the cluster will attach to."),
    ]
    zone_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="zoneName"),
        pydantic.Field(alias="zoneName", description="Zone name override for the cluster."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
