# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class KubernetesNodeRootVolume(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Name of the root volume.
    """

    size_gb: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="sizeGb"),
        pydantic.Field(alias="sizeGb", description="Root volume size, in gigabytes."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
