# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KubernetesConfigResponseDto(UniversalBaseModel):
    configdata: str = pydantic.Field()
    """
    The kubeconfig file content for connecting to the cluster. YAML-encoded; pipe to `~/.kube/config` or merge into an existing kubeconfig.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
