# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LoadBalancerRuleInstanceDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Identifier of the backend virtual machine.
    """

    name: str = pydantic.Field()
    """
    Name of the backend virtual machine.
    """

    state: str = pydantic.Field()
    """
    Current lifecycle state of the backend virtual machine.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
