# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MaxInstancesDto(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    Whether the operation succeeded.
    """

    max_instances: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maxInstances"),
        pydantic.Field(
            alias="maxInstances", description="Maximum number of WordPress instances the account may create."
        ),
    ] = None
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message describing why the operation failed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
