# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class NetworkAclRuleResponseDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the ACL rule.
    """

    acl_list_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="aclListId"),
        pydantic.Field(alias="aclListId", description="Identifier of the ACL list the rule belongs to."),
    ]
    number: int = pydantic.Field()
    """
    Rule number. Determines evaluation order within the ACL list.
    """

    protocol: str = pydantic.Field()
    """
    Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`.
    """

    cidr_list: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="cidrList"),
        pydantic.Field(
            alias="cidrList",
            description="Remote CIDR — source CIDR for `Ingress` rules, destination CIDR for `Egress` rules.",
        ),
    ]
    action: str = pydantic.Field()
    """
    Whether matching traffic is allowed or denied.
    """

    traffic_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="trafficType"),
        pydantic.Field(alias="trafficType", description="Direction of traffic the rule applies to."),
    ]
    start_port: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="startPort"),
        pydantic.Field(alias="startPort", description="Start of the port range. Used for `TCP` and `UDP` protocols."),
    ] = None
    end_port: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="endPort"),
        pydantic.Field(alias="endPort", description="End of the port range. Used for `TCP` and `UDP` protocols."),
    ] = None
    icmp_type: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="icmpType"),
        pydantic.Field(alias="icmpType", description="ICMP message type. Used for the `ICMP` protocol."),
    ] = None
    icmp_code: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="icmpCode"),
        pydantic.Field(alias="icmpCode", description="ICMP message code. Used for the `ICMP` protocol."),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the rule was created."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
