# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ObjectStorageUnitDto(UniversalBaseModel):
    storage_unit_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="storageUnitId"),
        pydantic.Field(alias="storageUnitId", description="Unique identifier for the storage unit."),
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the storage unit was created."),
    ]
    max_buckets: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maxBuckets"),
        pydantic.Field(
            alias="maxBuckets",
            description="Maximum number of buckets the storage unit may hold. Null means no limit (unlimited).",
        ),
    ] = None
    size_kb: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="sizeKb"),
        pydantic.Field(alias="sizeKb", description="Current usage of the storage unit, in kilobytes."),
    ] = None
    limit_kb: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="limitKb"),
        pydantic.Field(
            alias="limitKb",
            description="Total storage allowed on the storage unit, in kilobytes. Null means no limit (unlimited).",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
