# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProratedEstimateDto(UniversalBaseModel):
    days_remaining: float = pydantic.Field()
    """
    Number of days remaining until the next billing cycle
    """

    amount: float = pydantic.Field()
    """
    Prorated cost for the remaining days
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
