# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .snapshot_response_dto_type import SnapshotResponseDtoType


class SnapshotResponseDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier of the snapshot
    """

    name: str = pydantic.Field()
    """
    Name of the snapshot
    """

    size_gb: typing_extensions.Annotated[
        int, FieldMetadata(alias="sizeGb"), pydantic.Field(alias="sizeGb", description="Size of the snapshot in GB")
    ]
    status: str = pydantic.Field()
    """
    Current status of the snapshot
    """

    type: typing.Optional[SnapshotResponseDtoType] = pydantic.Field(default=None)
    """
    Type of the snapshot. Null when the source volume has no recorded type (rare; typically legacy snapshots).
    """

    volume_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="volumeId"),
        pydantic.Field(alias="volumeId", description="ID of the volume the snapshot was created from, if any"),
    ]
    region: str = pydantic.Field()
    """
    Label of the region where the snapshot is located
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the snapshot was created"),
    ]
    vm_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="vmId"),
        pydantic.Field(alias="vmId", description="ID of the virtual machine the snapshot was created from, if any"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
