# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class VmPackageDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    VM Package ID
    """

    label: str = pydantic.Field()
    """
    Internal label identifier for the VM Package
    """

    description: str = pydantic.Field()
    """
    Human-readable display name for the VM Package
    """

    min_cpu: typing_extensions.Annotated[
        float, FieldMetadata(alias="minCpu"), pydantic.Field(alias="minCpu", description="Minimum number of CPUs")
    ]
    max_cpu: typing_extensions.Annotated[
        float, FieldMetadata(alias="maxCpu"), pydantic.Field(alias="maxCpu", description="Maximum number of CPUs")
    ]
    min_root_disk_gb: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="minRootDiskGb"),
        pydantic.Field(alias="minRootDiskGb", description="Minimum root disk size in GB"),
    ]
    max_root_disk_gb: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="maxRootDiskGb"),
        pydantic.Field(alias="maxRootDiskGb", description="Maximum root disk size in GB"),
    ]
    min_memory_mb: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="minMemoryMb"),
        pydantic.Field(alias="minMemoryMb", description="Minimum memory in MB"),
    ]
    max_memory_mb: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="maxMemoryMb"),
        pydantic.Field(alias="maxMemoryMb", description="Maximum memory in MB"),
    ]
    tier: str = pydantic.Field()
    """
    Performance tier
    """

    zones: typing.List[str] = pydantic.Field()
    """
    Array of zone IDs where this package is available
    """

    cpu: int = pydantic.Field()
    """
    Number of CPUs (deprecated, use minCpu instead)
    """

    root_disk_gb: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="rootDiskGb"),
        pydantic.Field(alias="rootDiskGb", description="Root disk size in GB (deprecated, use minRootDiskGb instead)"),
    ]
    memory_mb: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="memoryMb"),
        pydantic.Field(alias="memoryMb", description="Memory in MB (deprecated, use minMemoryMb instead)"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
