# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class VmSpecsDto(UniversalBaseModel):
    vcpu: float = pydantic.Field()
    """
    Number of virtual CPUs
    """

    memory_mb: typing_extensions.Annotated[
        int, FieldMetadata(alias="memoryMb"), pydantic.Field(alias="memoryMb", description="Memory in MB")
    ]
    root_disk_gb: typing_extensions.Annotated[
        int, FieldMetadata(alias="rootDiskGb"), pydantic.Field(alias="rootDiskGb", description="Root disk size in GB")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
