# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class VolumeResponseDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier of the volume
    """

    name: str = pydantic.Field()
    """
    Name of the volume
    """

    size_gb: typing_extensions.Annotated[
        int, FieldMetadata(alias="sizeGb"), pydantic.Field(alias="sizeGb", description="Size of the volume in GB")
    ]
    status: str = pydantic.Field()
    """
    Current status of the volume
    """

    vm_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="vmId"),
        pydantic.Field(alias="vmId", description="ID of the VM the volume is attached to. Null for detached volumes."),
    ] = None
    region: str = pydantic.Field()
    """
    Label of the region where the volume is located
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the volume was created"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
