# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WordPressInstanceDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the WordPress instance.
    """

    username: str = pydantic.Field()
    """
    WordPress username on the hosting platform.
    """

    name: str = pydantic.Field()
    """
    Display name for the WordPress instance.
    """

    package_label: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="packageLabel"),
        pydantic.Field(alias="packageLabel", description="Label of the package currently applied to the instance."),
    ]
    package_display_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="packageDisplayName"),
        pydantic.Field(
            alias="packageDisplayName", description="Display name of the package currently applied to the instance."
        ),
    ]
    rate_monthly: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="rateMonthly"),
        pydantic.Field(alias="rateMonthly", description="Monthly billing rate for the current package, in US dollars."),
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the WordPress instance was provisioned."),
    ]
    deleted_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="deletedAt"),
        pydantic.Field(
            alias="deletedAt", description="When the WordPress instance was deleted. Omitted if still active."
        ),
    ] = None
    ready: bool = pydantic.Field()
    """
    Whether the WordPress instance is fully provisioned and ready to use.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
