# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.cost_estimate_response_dto import CostEstimateResponseDto
from ..types.kubernetes_cluster_response import KubernetesClusterResponse
from ..types.kubernetes_config_response_dto import KubernetesConfigResponseDto
from .raw_client import AsyncRawKubernetesClient, RawKubernetesClient
from .types.cluster_power_kubernetes_request_action import ClusterPowerKubernetesRequestAction
from .types.list_clusters_kubernetes_response import ListClustersKubernetesResponse
from .types.list_packages_kubernetes_response import ListPackagesKubernetesResponse
from .types.list_versions_kubernetes_response import ListVersionsKubernetesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class KubernetesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawKubernetesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawKubernetesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawKubernetesClient
        """
        return self._raw_client

    def list_versions_kubernetes(
        self,
        *,
        current_version: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListVersionsKubernetesResponse:
        """
        Returns all available versions. If current_version is provided, returns only versions that are valid upgrade targets (higher version, max one minor version jump).

        Parameters
        ----------
        current_version : typing.Optional[str]
            Current cluster version to filter upgradeable versions from

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListVersionsKubernetesResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.list_versions_kubernetes(
            current_version="1.28.4",
        )
        """
        _response = self._raw_client.list_versions_kubernetes(
            current_version=current_version, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def list_packages_kubernetes(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPackagesKubernetesResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPackagesKubernetesResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.list_packages_kubernetes()
        """
        _response = self._raw_client.list_packages_kubernetes(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def list_clusters_kubernetes(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListClustersKubernetesResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListClustersKubernetesResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.list_clusters_kubernetes()
        """
        _response = self._raw_client.list_clusters_kubernetes(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def get_cluster_kubernetes(
        self, id: str, *, details: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> KubernetesClusterResponse:
        """
        Returns cluster details. Set details=true to include node instances and attached storage volumes.

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        details : typing.Optional[bool]
            Include node instances and storage volumes in the response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KubernetesClusterResponse
            Kubernetes cluster details

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.get_cluster_kubernetes(
            id="123e4567-e89b-12d3-a456-426614174000",
            details=False,
        )
        """
        _response = self._raw_client.get_cluster_kubernetes(id, details=details, request_options=request_options)
        return _response.data

    def delete_cluster_kubernetes(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.delete_cluster_kubernetes(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.delete_cluster_kubernetes(id, request_options=request_options)
        return _response.data

    def create_cluster_kubernetes(
        self,
        *,
        name: str,
        package: str,
        region: str,
        version: str,
        control_nodes: float,
        worker_nodes: float,
        description: typing.Optional[str] = OMIT,
        network_id: typing.Optional[str] = OMIT,
        keypair: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KubernetesClusterResponse:
        """
        Creates a new Kubernetes cluster for the authenticated account. To preview pricing without creating anything, use POST /kubernetes/cost-estimate.

        Parameters
        ----------
        name : str
            Name of the cluster

        package : str
            Package label to use for the cluster

        region : str
            Region where to deploy the cluster

        version : str
            Kubernetes version to use (semantic version)

        control_nodes : float
            Number of control plane nodes

        worker_nodes : float
            Number of worker nodes

        description : typing.Optional[str]
            Description of the cluster

        network_id : typing.Optional[str]
            Network ID to use for the cluster

        keypair : typing.Optional[str]
            SSH keypair name to use for cluster nodes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KubernetesClusterResponse
            The cluster has been successfully created

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.create_cluster_kubernetes(
            name="my-cluster",
            package="my-package",
            region="us-west-0",
            version="1.28.4",
            control_nodes=1.0,
            worker_nodes=3.0,
        )
        """
        _response = self._raw_client.create_cluster_kubernetes(
            name=name,
            package=package,
            region=region,
            version=version,
            control_nodes=control_nodes,
            worker_nodes=worker_nodes,
            description=description,
            network_id=network_id,
            keypair=keypair,
            request_options=request_options,
        )
        return _response.data

    def get_cost_estimate_kubernetes(
        self,
        *,
        name: str,
        package: str,
        region: str,
        version: str,
        control_nodes: float,
        worker_nodes: float,
        description: typing.Optional[str] = OMIT,
        network_id: typing.Optional[str] = OMIT,
        keypair: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CostEstimateResponseDto:
        """
        Returns the estimated cost for a cluster with the given configuration without creating it. Accepts the same body as create.

        Parameters
        ----------
        name : str
            Name of the cluster

        package : str
            Package label to use for the cluster

        region : str
            Region where to deploy the cluster

        version : str
            Kubernetes version to use (semantic version)

        control_nodes : float
            Number of control plane nodes

        worker_nodes : float
            Number of worker nodes

        description : typing.Optional[str]
            Description of the cluster

        network_id : typing.Optional[str]
            Network ID to use for the cluster

        keypair : typing.Optional[str]
            SSH keypair name to use for cluster nodes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CostEstimateResponseDto
            Cost estimate for the Kubernetes cluster

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.get_cost_estimate_kubernetes(
            name="my-cluster",
            package="my-package",
            region="us-west-0",
            version="1.28.4",
            control_nodes=1.0,
            worker_nodes=3.0,
        )
        """
        _response = self._raw_client.get_cost_estimate_kubernetes(
            name=name,
            package=package,
            region=region,
            version=version,
            control_nodes=control_nodes,
            worker_nodes=worker_nodes,
            description=description,
            network_id=network_id,
            keypair=keypair,
            request_options=request_options,
        )
        return _response.data

    def cluster_power_kubernetes(
        self,
        id: str,
        *,
        action: ClusterPowerKubernetesRequestAction,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Start or stop a Kubernetes cluster

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        action : ClusterPowerKubernetesRequestAction
            Power action to perform

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.cluster_power_kubernetes(
            id="123e4567-e89b-12d3-a456-426614174000",
            action="start",
        )
        """
        _response = self._raw_client.cluster_power_kubernetes(id, action=action, request_options=request_options)
        return _response.data

    def get_cluster_config_kubernetes(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> KubernetesConfigResponseDto:
        """
        Returns the kubeconfig file content for connecting to the cluster

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KubernetesConfigResponseDto
            The kubeconfig content

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.get_cluster_config_kubernetes(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.get_cluster_config_kubernetes(id, request_options=request_options)
        return _response.data

    def scale_cluster_kubernetes(
        self,
        id: str,
        *,
        worker_nodes: typing.Optional[float] = OMIT,
        autoscaling_enabled: typing.Optional[bool] = OMIT,
        min_workers: typing.Optional[float] = OMIT,
        max_workers: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Scale worker nodes, or enable/disable autoscaling with min/max bounds. At least one parameter must be provided.

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        worker_nodes : typing.Optional[float]
            Number of worker nodes

        autoscaling_enabled : typing.Optional[bool]
            Enable or disable autoscaling

        min_workers : typing.Optional[float]
            Minimum number of worker nodes when autoscaling is enabled

        max_workers : typing.Optional[float]
            Maximum number of worker nodes when autoscaling is enabled

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.scale_cluster_kubernetes(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.scale_cluster_kubernetes(
            id,
            worker_nodes=worker_nodes,
            autoscaling_enabled=autoscaling_enabled,
            min_workers=min_workers,
            max_workers=max_workers,
            request_options=request_options,
        )
        return _response.data

    def upgrade_cluster_kubernetes(
        self, id: str, *, version: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Upgrade to a newer Kubernetes version. Use GET /versions to list available versions.

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        version : str
            Kubernetes version to upgrade to (semantic version)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.kubernetes.upgrade_cluster_kubernetes(
            id="123e4567-e89b-12d3-a456-426614174000",
            version="1.29.0",
        )
        """
        _response = self._raw_client.upgrade_cluster_kubernetes(id, version=version, request_options=request_options)
        return _response.data


class AsyncKubernetesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawKubernetesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawKubernetesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawKubernetesClient
        """
        return self._raw_client

    async def list_versions_kubernetes(
        self,
        *,
        current_version: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListVersionsKubernetesResponse:
        """
        Returns all available versions. If current_version is provided, returns only versions that are valid upgrade targets (higher version, max one minor version jump).

        Parameters
        ----------
        current_version : typing.Optional[str]
            Current cluster version to filter upgradeable versions from

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListVersionsKubernetesResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.list_versions_kubernetes(
                current_version="1.28.4",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_versions_kubernetes(
            current_version=current_version, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def list_packages_kubernetes(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPackagesKubernetesResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPackagesKubernetesResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.list_packages_kubernetes()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_packages_kubernetes(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def list_clusters_kubernetes(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListClustersKubernetesResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListClustersKubernetesResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.list_clusters_kubernetes()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_clusters_kubernetes(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def get_cluster_kubernetes(
        self, id: str, *, details: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> KubernetesClusterResponse:
        """
        Returns cluster details. Set details=true to include node instances and attached storage volumes.

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        details : typing.Optional[bool]
            Include node instances and storage volumes in the response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KubernetesClusterResponse
            Kubernetes cluster details

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.get_cluster_kubernetes(
                id="123e4567-e89b-12d3-a456-426614174000",
                details=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cluster_kubernetes(id, details=details, request_options=request_options)
        return _response.data

    async def delete_cluster_kubernetes(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.delete_cluster_kubernetes(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_cluster_kubernetes(id, request_options=request_options)
        return _response.data

    async def create_cluster_kubernetes(
        self,
        *,
        name: str,
        package: str,
        region: str,
        version: str,
        control_nodes: float,
        worker_nodes: float,
        description: typing.Optional[str] = OMIT,
        network_id: typing.Optional[str] = OMIT,
        keypair: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KubernetesClusterResponse:
        """
        Creates a new Kubernetes cluster for the authenticated account. To preview pricing without creating anything, use POST /kubernetes/cost-estimate.

        Parameters
        ----------
        name : str
            Name of the cluster

        package : str
            Package label to use for the cluster

        region : str
            Region where to deploy the cluster

        version : str
            Kubernetes version to use (semantic version)

        control_nodes : float
            Number of control plane nodes

        worker_nodes : float
            Number of worker nodes

        description : typing.Optional[str]
            Description of the cluster

        network_id : typing.Optional[str]
            Network ID to use for the cluster

        keypair : typing.Optional[str]
            SSH keypair name to use for cluster nodes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KubernetesClusterResponse
            The cluster has been successfully created

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.create_cluster_kubernetes(
                name="my-cluster",
                package="my-package",
                region="us-west-0",
                version="1.28.4",
                control_nodes=1.0,
                worker_nodes=3.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_cluster_kubernetes(
            name=name,
            package=package,
            region=region,
            version=version,
            control_nodes=control_nodes,
            worker_nodes=worker_nodes,
            description=description,
            network_id=network_id,
            keypair=keypair,
            request_options=request_options,
        )
        return _response.data

    async def get_cost_estimate_kubernetes(
        self,
        *,
        name: str,
        package: str,
        region: str,
        version: str,
        control_nodes: float,
        worker_nodes: float,
        description: typing.Optional[str] = OMIT,
        network_id: typing.Optional[str] = OMIT,
        keypair: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CostEstimateResponseDto:
        """
        Returns the estimated cost for a cluster with the given configuration without creating it. Accepts the same body as create.

        Parameters
        ----------
        name : str
            Name of the cluster

        package : str
            Package label to use for the cluster

        region : str
            Region where to deploy the cluster

        version : str
            Kubernetes version to use (semantic version)

        control_nodes : float
            Number of control plane nodes

        worker_nodes : float
            Number of worker nodes

        description : typing.Optional[str]
            Description of the cluster

        network_id : typing.Optional[str]
            Network ID to use for the cluster

        keypair : typing.Optional[str]
            SSH keypair name to use for cluster nodes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CostEstimateResponseDto
            Cost estimate for the Kubernetes cluster

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.get_cost_estimate_kubernetes(
                name="my-cluster",
                package="my-package",
                region="us-west-0",
                version="1.28.4",
                control_nodes=1.0,
                worker_nodes=3.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cost_estimate_kubernetes(
            name=name,
            package=package,
            region=region,
            version=version,
            control_nodes=control_nodes,
            worker_nodes=worker_nodes,
            description=description,
            network_id=network_id,
            keypair=keypair,
            request_options=request_options,
        )
        return _response.data

    async def cluster_power_kubernetes(
        self,
        id: str,
        *,
        action: ClusterPowerKubernetesRequestAction,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Start or stop a Kubernetes cluster

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        action : ClusterPowerKubernetesRequestAction
            Power action to perform

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.cluster_power_kubernetes(
                id="123e4567-e89b-12d3-a456-426614174000",
                action="start",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cluster_power_kubernetes(id, action=action, request_options=request_options)
        return _response.data

    async def get_cluster_config_kubernetes(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> KubernetesConfigResponseDto:
        """
        Returns the kubeconfig file content for connecting to the cluster

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KubernetesConfigResponseDto
            The kubeconfig content

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.get_cluster_config_kubernetes(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cluster_config_kubernetes(id, request_options=request_options)
        return _response.data

    async def scale_cluster_kubernetes(
        self,
        id: str,
        *,
        worker_nodes: typing.Optional[float] = OMIT,
        autoscaling_enabled: typing.Optional[bool] = OMIT,
        min_workers: typing.Optional[float] = OMIT,
        max_workers: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Scale worker nodes, or enable/disable autoscaling with min/max bounds. At least one parameter must be provided.

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        worker_nodes : typing.Optional[float]
            Number of worker nodes

        autoscaling_enabled : typing.Optional[bool]
            Enable or disable autoscaling

        min_workers : typing.Optional[float]
            Minimum number of worker nodes when autoscaling is enabled

        max_workers : typing.Optional[float]
            Maximum number of worker nodes when autoscaling is enabled

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.scale_cluster_kubernetes(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scale_cluster_kubernetes(
            id,
            worker_nodes=worker_nodes,
            autoscaling_enabled=autoscaling_enabled,
            min_workers=min_workers,
            max_workers=max_workers,
            request_options=request_options,
        )
        return _response.data

    async def upgrade_cluster_kubernetes(
        self, id: str, *, version: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Upgrade to a newer Kubernetes version. Use GET /versions to list available versions.

        Parameters
        ----------
        id : str
            ID of the Kubernetes cluster

        version : str
            Kubernetes version to upgrade to (semantic version)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.kubernetes.upgrade_cluster_kubernetes(
                id="123e4567-e89b-12d3-a456-426614174000",
                version="1.29.0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upgrade_cluster_kubernetes(
            id, version=version, request_options=request_options
        )
        return _response.data
