# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.firewall_rule_response_dto import FirewallRuleResponseDto
from .raw_client import AsyncRawFirewallRulesClient, RawFirewallRulesClient
from .types.create_firewall_rule_dto_protocol import CreateFirewallRuleDtoProtocol
from .types.create_firewall_rule_dto_type import CreateFirewallRuleDtoType
from .types.list_firewall_rules_response import ListFirewallRulesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FirewallRulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFirewallRulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFirewallRulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFirewallRulesClient
        """
        return self._raw_client

    def list_firewall_rules(
        self,
        ip_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFirewallRulesResponse:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFirewallRulesResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.firewall_rules.list_firewall_rules(
            ip_id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.list_firewall_rules(
            ip_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_firewall_rules(
        self,
        ip_id: str,
        *,
        protocol: CreateFirewallRuleDtoProtocol,
        source_cidr_list: str,
        start_port: typing.Optional[int] = OMIT,
        end_port: typing.Optional[int] = OMIT,
        type: typing.Optional[CreateFirewallRuleDtoType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallRuleResponseDto:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        protocol : CreateFirewallRuleDtoProtocol
            Protocol the rule applies to.

        source_cidr_list : str
            Source CIDR allowed to reach the rule target.

        start_port : typing.Optional[int]
            Start of the port range (1-65535). Required for TCP and UDP.

        end_port : typing.Optional[int]
            End of the port range (1-65535). Must be greater than or equal to `startPort`.

        type : typing.Optional[CreateFirewallRuleDtoType]
            Direction of traffic this rule applies to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallRuleResponseDto
            The firewall rule has been created

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.firewall_rules.create_firewall_rules(
            ip_id="123e4567-e89b-12d3-a456-426614174000",
            protocol="TCP",
            source_cidr_list="10.0.0.0/24",
        )
        """
        _response = self._raw_client.create_firewall_rules(
            ip_id,
            protocol=protocol,
            source_cidr_list=source_cidr_list,
            start_port=start_port,
            end_port=end_port,
            type=type,
            request_options=request_options,
        )
        return _response.data

    def delete_firewall_rules(self, rule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        rule_id : str
            ID of the firewall rule to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.firewall_rules.delete_firewall_rules(
            rule_id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.delete_firewall_rules(rule_id, request_options=request_options)
        return _response.data


class AsyncFirewallRulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFirewallRulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFirewallRulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFirewallRulesClient
        """
        return self._raw_client

    async def list_firewall_rules(
        self,
        ip_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFirewallRulesResponse:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFirewallRulesResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.firewall_rules.list_firewall_rules(
                ip_id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_firewall_rules(
            ip_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_firewall_rules(
        self,
        ip_id: str,
        *,
        protocol: CreateFirewallRuleDtoProtocol,
        source_cidr_list: str,
        start_port: typing.Optional[int] = OMIT,
        end_port: typing.Optional[int] = OMIT,
        type: typing.Optional[CreateFirewallRuleDtoType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FirewallRuleResponseDto:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        protocol : CreateFirewallRuleDtoProtocol
            Protocol the rule applies to.

        source_cidr_list : str
            Source CIDR allowed to reach the rule target.

        start_port : typing.Optional[int]
            Start of the port range (1-65535). Required for TCP and UDP.

        end_port : typing.Optional[int]
            End of the port range (1-65535). Must be greater than or equal to `startPort`.

        type : typing.Optional[CreateFirewallRuleDtoType]
            Direction of traffic this rule applies to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FirewallRuleResponseDto
            The firewall rule has been created

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.firewall_rules.create_firewall_rules(
                ip_id="123e4567-e89b-12d3-a456-426614174000",
                protocol="TCP",
                source_cidr_list="10.0.0.0/24",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_firewall_rules(
            ip_id,
            protocol=protocol,
            source_cidr_list=source_cidr_list,
            start_port=start_port,
            end_port=end_port,
            type=type,
            request_options=request_options,
        )
        return _response.data

    async def delete_firewall_rules(
        self, rule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        rule_id : str
            ID of the firewall rule to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.firewall_rules.delete_firewall_rules(
                rule_id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_firewall_rules(rule_id, request_options=request_options)
        return _response.data
