# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.access_key_dto import AccessKeyDto
from ..types.cost_estimate_response_dto import CostEstimateResponseDto
from ..types.object_storage_success_response_dto import ObjectStorageSuccessResponseDto
from .raw_client import AsyncRawObjectStorageClient, RawObjectStorageClient
from .types.list_buckets_object_storage_response import ListBucketsObjectStorageResponse
from .types.list_units_object_storage_response import ListUnitsObjectStorageResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ObjectStorageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawObjectStorageClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawObjectStorageClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawObjectStorageClient
        """
        return self._raw_client

    def list_units_object_storage(
        self,
        *,
        usage: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUnitsObjectStorageResponse:
        """
        Returns all non-deleted object storage units (UIDs) for the authenticated account

        Parameters
        ----------
        usage : typing.Optional[bool]
            Include latest usage report for each storage unit

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUnitsObjectStorageResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.list_units_object_storage(
            usage=False,
        )
        """
        _response = self._raw_client.list_units_object_storage(
            usage=usage, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_unit_object_storage(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ObjectStorageSuccessResponseDto:
        """
        Creates a new object storage unit (RGW user) for the authenticated account. To preview pricing without creating anything, use POST /object-storage/units/cost-estimate.

        Parameters
        ----------
        name : str
            Storage unit name. Alphanumeric characters only.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Storage unit created successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.create_unit_object_storage(
            name="storageunit01",
        )
        """
        _response = self._raw_client.create_unit_object_storage(name=name, request_options=request_options)
        return _response.data

    def list_buckets_object_storage(
        self,
        storage_unit_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBucketsObjectStorageResponse:
        """
        Returns all buckets and their statistics for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBucketsObjectStorageResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.list_buckets_object_storage(
            storage_unit_id="tenant$user",
        )
        """
        _response = self._raw_client.list_buckets_object_storage(
            storage_unit_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_bucket_object_storage(
        self, storage_unit_id: str, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ObjectStorageSuccessResponseDto:
        """
        Creates a new bucket for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        name : str
            Bucket name. Lowercase letters, numbers, dots, and hyphens only; must start and end with a letter or number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Bucket created successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.create_bucket_object_storage(
            storage_unit_id="tenant$user",
            name="my-storage-bucket",
        )
        """
        _response = self._raw_client.create_bucket_object_storage(
            storage_unit_id, name=name, request_options=request_options
        )
        return _response.data

    def get_keys_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AccessKeyDto:
        """
        Returns all access keys (access key and secret key pairs) for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccessKeyDto
            Access keys

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.get_keys_object_storage(
            storage_unit_id="tenant$user",
        )
        """
        _response = self._raw_client.get_keys_object_storage(storage_unit_id, request_options=request_options)
        return _response.data

    def get_cost_estimate_object_storage(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CostEstimateResponseDto:
        """
        Returns the estimated cost of an object storage unit without creating one.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CostEstimateResponseDto
            Cost estimate for the storage unit

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.get_cost_estimate_object_storage()
        """
        _response = self._raw_client.get_cost_estimate_object_storage(request_options=request_options)
        return _response.data

    def set_user_quota_object_storage(
        self,
        storage_unit_id: str,
        *,
        max_size_gb: typing.Optional[float] = OMIT,
        remove_limit: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ObjectStorageSuccessResponseDto:
        """
        Sets the user quota limit for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        max_size_gb : typing.Optional[float]
            Maximum total size for the storage unit, in gigabytes.

        remove_limit : typing.Optional[bool]
            When true, removes any existing storage limit instead of setting a value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            User quota set successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.set_user_quota_object_storage(
            storage_unit_id="tenant$user",
        )
        """
        _response = self._raw_client.set_user_quota_object_storage(
            storage_unit_id, max_size_gb=max_size_gb, remove_limit=remove_limit, request_options=request_options
        )
        return _response.data

    def delete_unit_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ObjectStorageSuccessResponseDto:
        """
        Deletes an object storage unit (RGW user)

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Storage unit deleted successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.delete_unit_object_storage(
            storage_unit_id="tenant$user",
        )
        """
        _response = self._raw_client.delete_unit_object_storage(storage_unit_id, request_options=request_options)
        return _response.data

    def delete_bucket_object_storage(
        self,
        storage_unit_id: str,
        bucket_name: str,
        *,
        purge_objects: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ObjectStorageSuccessResponseDto:
        """
        Deletes a bucket from the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        bucket_name : str
            Bucket name

        purge_objects : typing.Optional[bool]
            Whether to purge objects in the bucket (default: true)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Bucket deleted successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.object_storage.delete_bucket_object_storage(
            storage_unit_id="tenant$user",
            bucket_name="my-bucket",
            purge_objects=True,
        )
        """
        _response = self._raw_client.delete_bucket_object_storage(
            storage_unit_id, bucket_name, purge_objects=purge_objects, request_options=request_options
        )
        return _response.data


class AsyncObjectStorageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawObjectStorageClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawObjectStorageClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawObjectStorageClient
        """
        return self._raw_client

    async def list_units_object_storage(
        self,
        *,
        usage: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUnitsObjectStorageResponse:
        """
        Returns all non-deleted object storage units (UIDs) for the authenticated account

        Parameters
        ----------
        usage : typing.Optional[bool]
            Include latest usage report for each storage unit

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUnitsObjectStorageResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.list_units_object_storage(
                usage=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_units_object_storage(
            usage=usage, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_unit_object_storage(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ObjectStorageSuccessResponseDto:
        """
        Creates a new object storage unit (RGW user) for the authenticated account. To preview pricing without creating anything, use POST /object-storage/units/cost-estimate.

        Parameters
        ----------
        name : str
            Storage unit name. Alphanumeric characters only.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Storage unit created successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.create_unit_object_storage(
                name="storageunit01",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_unit_object_storage(name=name, request_options=request_options)
        return _response.data

    async def list_buckets_object_storage(
        self,
        storage_unit_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBucketsObjectStorageResponse:
        """
        Returns all buckets and their statistics for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBucketsObjectStorageResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.list_buckets_object_storage(
                storage_unit_id="tenant$user",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_buckets_object_storage(
            storage_unit_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_bucket_object_storage(
        self, storage_unit_id: str, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ObjectStorageSuccessResponseDto:
        """
        Creates a new bucket for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        name : str
            Bucket name. Lowercase letters, numbers, dots, and hyphens only; must start and end with a letter or number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Bucket created successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.create_bucket_object_storage(
                storage_unit_id="tenant$user",
                name="my-storage-bucket",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_bucket_object_storage(
            storage_unit_id, name=name, request_options=request_options
        )
        return _response.data

    async def get_keys_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AccessKeyDto:
        """
        Returns all access keys (access key and secret key pairs) for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccessKeyDto
            Access keys

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.get_keys_object_storage(
                storage_unit_id="tenant$user",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_keys_object_storage(storage_unit_id, request_options=request_options)
        return _response.data

    async def get_cost_estimate_object_storage(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CostEstimateResponseDto:
        """
        Returns the estimated cost of an object storage unit without creating one.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CostEstimateResponseDto
            Cost estimate for the storage unit

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.get_cost_estimate_object_storage()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cost_estimate_object_storage(request_options=request_options)
        return _response.data

    async def set_user_quota_object_storage(
        self,
        storage_unit_id: str,
        *,
        max_size_gb: typing.Optional[float] = OMIT,
        remove_limit: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ObjectStorageSuccessResponseDto:
        """
        Sets the user quota limit for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        max_size_gb : typing.Optional[float]
            Maximum total size for the storage unit, in gigabytes.

        remove_limit : typing.Optional[bool]
            When true, removes any existing storage limit instead of setting a value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            User quota set successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.set_user_quota_object_storage(
                storage_unit_id="tenant$user",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_user_quota_object_storage(
            storage_unit_id, max_size_gb=max_size_gb, remove_limit=remove_limit, request_options=request_options
        )
        return _response.data

    async def delete_unit_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ObjectStorageSuccessResponseDto:
        """
        Deletes an object storage unit (RGW user)

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Storage unit deleted successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.delete_unit_object_storage(
                storage_unit_id="tenant$user",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_unit_object_storage(storage_unit_id, request_options=request_options)
        return _response.data

    async def delete_bucket_object_storage(
        self,
        storage_unit_id: str,
        bucket_name: str,
        *,
        purge_objects: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ObjectStorageSuccessResponseDto:
        """
        Deletes a bucket from the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        bucket_name : str
            Bucket name

        purge_objects : typing.Optional[bool]
            Whether to purge objects in the bucket (default: true)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ObjectStorageSuccessResponseDto
            Bucket deleted successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.object_storage.delete_bucket_object_storage(
                storage_unit_id="tenant$user",
                bucket_name="my-bucket",
                purge_objects=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_bucket_object_storage(
            storage_unit_id, bucket_name, purge_objects=purge_objects, request_options=request_options
        )
        return _response.data
