# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.access_key_dto import AccessKeyDto
from ..types.api_error_dto import ApiErrorDto
from ..types.cost_estimate_response_dto import CostEstimateResponseDto
from ..types.object_storage_success_response_dto import ObjectStorageSuccessResponseDto
from ..types.object_storage_unit_dto import ObjectStorageUnitDto
from .types.list_buckets_object_storage_response import ListBucketsObjectStorageResponse
from .types.list_units_object_storage_response import ListUnitsObjectStorageResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawObjectStorageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_units_object_storage(
        self,
        *,
        usage: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListUnitsObjectStorageResponse]:
        """
        Returns all non-deleted object storage units (UIDs) for the authenticated account

        Parameters
        ----------
        usage : typing.Optional[bool]
            Include latest usage report for each storage unit

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListUnitsObjectStorageResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/object-storage/units",
            method="GET",
            params={
                "usage": usage,
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListUnitsObjectStorageResponse,
                    parse_obj_as(
                        type_=ListUnitsObjectStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_unit_object_storage(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ObjectStorageUnitDto]:
        """
        Creates a new object storage unit for the authenticated account and returns it. The returned storageUnitId identifies the unit in all other object storage requests. To preview pricing without creating anything, use POST /object-storage/units/cost-estimate.

        Parameters
        ----------
        name : str
            Storage unit name. Alphanumeric characters only.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ObjectStorageUnitDto]
            The created storage unit
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/object-storage/units",
            method="POST",
            json={
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageUnitDto,
                    parse_obj_as(
                        type_=ObjectStorageUnitDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_buckets_object_storage(
        self,
        storage_unit_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListBucketsObjectStorageResponse]:
        """
        Returns all buckets and their statistics for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListBucketsObjectStorageResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/buckets",
            method="GET",
            params={
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListBucketsObjectStorageResponse,
                    parse_obj_as(
                        type_=ListBucketsObjectStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_bucket_object_storage(
        self, storage_unit_id: str, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Creates a new bucket for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        name : str
            Bucket name. Lowercase letters, numbers, dots, and hyphens only; must start and end with a letter or number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ObjectStorageSuccessResponseDto]
            Bucket created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/buckets",
            method="POST",
            json={
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_keys_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[AccessKeyDto]:
        """
        Returns all access keys (access key and secret key pairs) for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AccessKeyDto]
            Access keys
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/keys",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AccessKeyDto,
                    parse_obj_as(
                        type_=AccessKeyDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_cost_estimate_object_storage(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CostEstimateResponseDto]:
        """
        Returns the estimated cost of an object storage unit without creating one.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CostEstimateResponseDto]
            Cost estimate for the storage unit
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/object-storage/units/cost-estimate",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CostEstimateResponseDto,
                    parse_obj_as(
                        type_=CostEstimateResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def set_user_quota_object_storage(
        self,
        storage_unit_id: str,
        *,
        max_size_gb: typing.Optional[float] = OMIT,
        remove_limit: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Sets the user quota limit for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        max_size_gb : typing.Optional[float]
            Maximum total size for the storage unit, in gigabytes.

        remove_limit : typing.Optional[bool]
            When true, removes any existing storage limit instead of setting a value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ObjectStorageSuccessResponseDto]
            User quota set successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/quota",
            method="PUT",
            json={
                "maxSizeGb": max_size_gb,
                "removeLimit": remove_limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_unit_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Deletes an object storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ObjectStorageSuccessResponseDto]
            Storage unit deleted successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_bucket_object_storage(
        self,
        storage_unit_id: str,
        bucket_name: str,
        *,
        purge_objects: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Deletes a bucket from the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        bucket_name : str
            Bucket name

        purge_objects : typing.Optional[bool]
            Whether to purge objects in the bucket (default: true)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ObjectStorageSuccessResponseDto]
            Bucket deleted successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/buckets/{encode_path_param(bucket_name)}",
            method="DELETE",
            params={
                "purgeObjects": purge_objects,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawObjectStorageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_units_object_storage(
        self,
        *,
        usage: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListUnitsObjectStorageResponse]:
        """
        Returns all non-deleted object storage units (UIDs) for the authenticated account

        Parameters
        ----------
        usage : typing.Optional[bool]
            Include latest usage report for each storage unit

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListUnitsObjectStorageResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/object-storage/units",
            method="GET",
            params={
                "usage": usage,
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListUnitsObjectStorageResponse,
                    parse_obj_as(
                        type_=ListUnitsObjectStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_unit_object_storage(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ObjectStorageUnitDto]:
        """
        Creates a new object storage unit for the authenticated account and returns it. The returned storageUnitId identifies the unit in all other object storage requests. To preview pricing without creating anything, use POST /object-storage/units/cost-estimate.

        Parameters
        ----------
        name : str
            Storage unit name. Alphanumeric characters only.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ObjectStorageUnitDto]
            The created storage unit
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/object-storage/units",
            method="POST",
            json={
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageUnitDto,
                    parse_obj_as(
                        type_=ObjectStorageUnitDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_buckets_object_storage(
        self,
        storage_unit_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListBucketsObjectStorageResponse]:
        """
        Returns all buckets and their statistics for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListBucketsObjectStorageResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/buckets",
            method="GET",
            params={
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListBucketsObjectStorageResponse,
                    parse_obj_as(
                        type_=ListBucketsObjectStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_bucket_object_storage(
        self, storage_unit_id: str, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Creates a new bucket for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        name : str
            Bucket name. Lowercase letters, numbers, dots, and hyphens only; must start and end with a letter or number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ObjectStorageSuccessResponseDto]
            Bucket created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/buckets",
            method="POST",
            json={
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_keys_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[AccessKeyDto]:
        """
        Returns all access keys (access key and secret key pairs) for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AccessKeyDto]
            Access keys
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/keys",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AccessKeyDto,
                    parse_obj_as(
                        type_=AccessKeyDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_cost_estimate_object_storage(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CostEstimateResponseDto]:
        """
        Returns the estimated cost of an object storage unit without creating one.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CostEstimateResponseDto]
            Cost estimate for the storage unit
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/object-storage/units/cost-estimate",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CostEstimateResponseDto,
                    parse_obj_as(
                        type_=CostEstimateResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def set_user_quota_object_storage(
        self,
        storage_unit_id: str,
        *,
        max_size_gb: typing.Optional[float] = OMIT,
        remove_limit: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Sets the user quota limit for the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        max_size_gb : typing.Optional[float]
            Maximum total size for the storage unit, in gigabytes.

        remove_limit : typing.Optional[bool]
            When true, removes any existing storage limit instead of setting a value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ObjectStorageSuccessResponseDto]
            User quota set successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/quota",
            method="PUT",
            json={
                "maxSizeGb": max_size_gb,
                "removeLimit": remove_limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_unit_object_storage(
        self, storage_unit_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Deletes an object storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ObjectStorageSuccessResponseDto]
            Storage unit deleted successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_bucket_object_storage(
        self,
        storage_unit_id: str,
        bucket_name: str,
        *,
        purge_objects: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ObjectStorageSuccessResponseDto]:
        """
        Deletes a bucket from the specified storage unit

        Parameters
        ----------
        storage_unit_id : str
            Storage unit ID (UID)

        bucket_name : str
            Bucket name

        purge_objects : typing.Optional[bool]
            Whether to purge objects in the bucket (default: true)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ObjectStorageSuccessResponseDto]
            Bucket deleted successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/object-storage/units/{encode_path_param(storage_unit_id)}/buckets/{encode_path_param(bucket_name)}",
            method="DELETE",
            params={
                "purgeObjects": purge_objects,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ObjectStorageSuccessResponseDto,
                    parse_obj_as(
                        type_=ObjectStorageSuccessResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
