# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.api_error_dto import ApiErrorDto
from ..types.port_forwarding_rule_response_dto import PortForwardingRuleResponseDto
from .types.create_port_forwarding_rule_dto_protocol import CreatePortForwardingRuleDtoProtocol
from .types.list_port_forwarding_response import ListPortForwardingResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPortForwardingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_port_forwarding(
        self,
        ip_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListPortForwardingResponse]:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListPortForwardingResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/networks/firewall/port-forwarding/ip/{encode_path_param(ip_id)}",
            method="GET",
            params={
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPortForwardingResponse,
                    parse_obj_as(
                        type_=ListPortForwardingResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_port_forwarding(
        self,
        ip_id: str,
        *,
        private_port: str,
        public_port: str,
        protocol: CreatePortForwardingRuleDtoProtocol,
        vm_id: str,
        open_firewall: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PortForwardingRuleResponseDto]:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        private_port : str
            Port on the VM that traffic is forwarded to. Must be 1-65535.

        public_port : str
            Port on the public IP that receives the inbound traffic. Must be 1-65535.

        protocol : CreatePortForwardingRuleDtoProtocol
            Protocol the forwarding rule applies to.

        vm_id : str
            Identifier of the VM the forwarded traffic is delivered to.

        open_firewall : typing.Optional[str]
            When `true`, automatically creates a matching firewall rule alongside the port forwarding rule.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PortForwardingRuleResponseDto]
            The port forwarding rule has been created
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/networks/firewall/port-forwarding/ip/{encode_path_param(ip_id)}",
            method="POST",
            json={
                "privatePort": private_port,
                "publicPort": public_port,
                "protocol": protocol,
                "vmId": vm_id,
                "openFirewall": open_firewall,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PortForwardingRuleResponseDto,
                    parse_obj_as(
                        type_=PortForwardingRuleResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_port_forwarding(
        self, rule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        rule_id : str
            ID of the port forwarding rule to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/networks/firewall/port-forwarding/{encode_path_param(rule_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPortForwardingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_port_forwarding(
        self,
        ip_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListPortForwardingResponse]:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListPortForwardingResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/networks/firewall/port-forwarding/ip/{encode_path_param(ip_id)}",
            method="GET",
            params={
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPortForwardingResponse,
                    parse_obj_as(
                        type_=ListPortForwardingResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_port_forwarding(
        self,
        ip_id: str,
        *,
        private_port: str,
        public_port: str,
        protocol: CreatePortForwardingRuleDtoProtocol,
        vm_id: str,
        open_firewall: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PortForwardingRuleResponseDto]:
        """
        Parameters
        ----------
        ip_id : str
            ID of the public IP address

        private_port : str
            Port on the VM that traffic is forwarded to. Must be 1-65535.

        public_port : str
            Port on the public IP that receives the inbound traffic. Must be 1-65535.

        protocol : CreatePortForwardingRuleDtoProtocol
            Protocol the forwarding rule applies to.

        vm_id : str
            Identifier of the VM the forwarded traffic is delivered to.

        open_firewall : typing.Optional[str]
            When `true`, automatically creates a matching firewall rule alongside the port forwarding rule.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PortForwardingRuleResponseDto]
            The port forwarding rule has been created
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/networks/firewall/port-forwarding/ip/{encode_path_param(ip_id)}",
            method="POST",
            json={
                "privatePort": private_port,
                "publicPort": public_port,
                "protocol": protocol,
                "vmId": vm_id,
                "openFirewall": open_firewall,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PortForwardingRuleResponseDto,
                    parse_obj_as(
                        type_=PortForwardingRuleResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_port_forwarding(
        self, rule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        rule_id : str
            ID of the port forwarding rule to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/networks/firewall/port-forwarding/{encode_path_param(rule_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
