# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.egress_rule_response_dto import EgressRuleResponseDto
from .raw_client import AsyncRawEgressRulesClient, RawEgressRulesClient
from .types.list_by_network_egress_rules_response import ListByNetworkEgressRulesResponse
from .types.list_egress_rules_response import ListEgressRulesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EgressRulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEgressRulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEgressRulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEgressRulesClient
        """
        return self._raw_client

    def list_egress_rules(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEgressRulesResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEgressRulesResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.egress_rules.list_egress_rules()
        """
        _response = self._raw_client.list_egress_rules(page=page, page_size=page_size, request_options=request_options)
        return _response.data

    def create_egress_rules(
        self,
        *,
        protocol: str,
        start_port: typing.Optional[str] = OMIT,
        end_port: typing.Optional[str] = OMIT,
        source_cidr_list: typing.Optional[str] = OMIT,
        dest_cidr_list: typing.Optional[str] = OMIT,
        network_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EgressRuleResponseDto:
        """
        Parameters
        ----------
        protocol : str
            Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`.

        start_port : typing.Optional[str]
            Start of the port range the rule applies to.

        end_port : typing.Optional[str]
            End of the port range the rule applies to.

        source_cidr_list : typing.Optional[str]
            Source CIDR within the guest network CIDR. Omit to allow the entire network.

        dest_cidr_list : typing.Optional[str]
            Destination CIDR the traffic is allowed to reach. Defaults to `0.0.0.0/0`.

        network_id : typing.Optional[str]
            Identifier of the network the egress rule applies to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EgressRuleResponseDto
            The egress rule has been created

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.egress_rules.create_egress_rules(
            protocol="TCP",
        )
        """
        _response = self._raw_client.create_egress_rules(
            protocol=protocol,
            start_port=start_port,
            end_port=end_port,
            source_cidr_list=source_cidr_list,
            dest_cidr_list=dest_cidr_list,
            network_id=network_id,
            request_options=request_options,
        )
        return _response.data

    def list_by_network_egress_rules(
        self,
        network_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListByNetworkEgressRulesResponse:
        """
        Parameters
        ----------
        network_id : str
            ID of the network

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListByNetworkEgressRulesResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.egress_rules.list_by_network_egress_rules(
            network_id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.list_by_network_egress_rules(
            network_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def get_egress_rules(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EgressRuleResponseDto:
        """
        Parameters
        ----------
        id : str
            ID of the egress rule

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EgressRuleResponseDto
            The egress rule details

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.egress_rules.get_egress_rules(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.get_egress_rules(id, request_options=request_options)
        return _response.data

    def update_egress_rules(
        self,
        id: str,
        *,
        source_cidr_list: typing.Optional[str] = OMIT,
        dest_cidr_list: typing.Optional[str] = OMIT,
        start_port: typing.Optional[str] = OMIT,
        end_port: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EgressRuleResponseDto:
        """
        Parameters
        ----------
        id : str
            ID of the egress rule

        source_cidr_list : typing.Optional[str]
            Source CIDR within the guest network CIDR.

        dest_cidr_list : typing.Optional[str]
            Destination CIDR the traffic is allowed to reach.

        start_port : typing.Optional[str]
            Start of the port range the rule applies to.

        end_port : typing.Optional[str]
            End of the port range the rule applies to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EgressRuleResponseDto
            The egress rule has been updated

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.egress_rules.update_egress_rules(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.update_egress_rules(
            id,
            source_cidr_list=source_cidr_list,
            dest_cidr_list=dest_cidr_list,
            start_port=start_port,
            end_port=end_port,
            request_options=request_options,
        )
        return _response.data

    def delete_egress_rules(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            ID of the egress rule to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.egress_rules.delete_egress_rules(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.delete_egress_rules(id, request_options=request_options)
        return _response.data


class AsyncEgressRulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEgressRulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEgressRulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEgressRulesClient
        """
        return self._raw_client

    async def list_egress_rules(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEgressRulesResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEgressRulesResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.egress_rules.list_egress_rules()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_egress_rules(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_egress_rules(
        self,
        *,
        protocol: str,
        start_port: typing.Optional[str] = OMIT,
        end_port: typing.Optional[str] = OMIT,
        source_cidr_list: typing.Optional[str] = OMIT,
        dest_cidr_list: typing.Optional[str] = OMIT,
        network_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EgressRuleResponseDto:
        """
        Parameters
        ----------
        protocol : str
            Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`.

        start_port : typing.Optional[str]
            Start of the port range the rule applies to.

        end_port : typing.Optional[str]
            End of the port range the rule applies to.

        source_cidr_list : typing.Optional[str]
            Source CIDR within the guest network CIDR. Omit to allow the entire network.

        dest_cidr_list : typing.Optional[str]
            Destination CIDR the traffic is allowed to reach. Defaults to `0.0.0.0/0`.

        network_id : typing.Optional[str]
            Identifier of the network the egress rule applies to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EgressRuleResponseDto
            The egress rule has been created

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.egress_rules.create_egress_rules(
                protocol="TCP",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_egress_rules(
            protocol=protocol,
            start_port=start_port,
            end_port=end_port,
            source_cidr_list=source_cidr_list,
            dest_cidr_list=dest_cidr_list,
            network_id=network_id,
            request_options=request_options,
        )
        return _response.data

    async def list_by_network_egress_rules(
        self,
        network_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListByNetworkEgressRulesResponse:
        """
        Parameters
        ----------
        network_id : str
            ID of the network

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListByNetworkEgressRulesResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.egress_rules.list_by_network_egress_rules(
                network_id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_by_network_egress_rules(
            network_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def get_egress_rules(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EgressRuleResponseDto:
        """
        Parameters
        ----------
        id : str
            ID of the egress rule

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EgressRuleResponseDto
            The egress rule details

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.egress_rules.get_egress_rules(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_egress_rules(id, request_options=request_options)
        return _response.data

    async def update_egress_rules(
        self,
        id: str,
        *,
        source_cidr_list: typing.Optional[str] = OMIT,
        dest_cidr_list: typing.Optional[str] = OMIT,
        start_port: typing.Optional[str] = OMIT,
        end_port: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EgressRuleResponseDto:
        """
        Parameters
        ----------
        id : str
            ID of the egress rule

        source_cidr_list : typing.Optional[str]
            Source CIDR within the guest network CIDR.

        dest_cidr_list : typing.Optional[str]
            Destination CIDR the traffic is allowed to reach.

        start_port : typing.Optional[str]
            Start of the port range the rule applies to.

        end_port : typing.Optional[str]
            End of the port range the rule applies to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EgressRuleResponseDto
            The egress rule has been updated

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.egress_rules.update_egress_rules(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_egress_rules(
            id,
            source_cidr_list=source_cidr_list,
            dest_cidr_list=dest_cidr_list,
            start_port=start_port,
            end_port=end_port,
            request_options=request_options,
        )
        return _response.data

    async def delete_egress_rules(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        id : str
            ID of the egress rule to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.egress_rules.delete_egress_rules(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_egress_rules(id, request_options=request_options)
        return _response.data
