# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...types.cluster_detail_response_dto import ClusterDetailResponseDto
from ...types.paginated_response_dto import PaginatedResponseDto


class ListDatabasesResponse(PaginatedResponseDto):
    data: typing.List[ClusterDetailResponseDto]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
