# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...types.database_offering_response_dto import DatabaseOfferingResponseDto
from ...types.paginated_response_dto import PaginatedResponseDto


class ListDatabaseOfferingsResponse(PaginatedResponseDto):
    data: typing.List[DatabaseOfferingResponseDto]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
