# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...types.paginated_response_dto import PaginatedResponseDto
from ...types.snapshot_response_dto import SnapshotResponseDto


class ListSnapshotsResponse(PaginatedResponseDto):
    data: typing.List[SnapshotResponseDto]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
