# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.cost_estimate_response_dto import CostEstimateResponseDto
from ..types.volume_deletion_response_dto import VolumeDeletionResponseDto
from ..types.volume_operation_response_dto import VolumeOperationResponseDto
from ..types.volume_response_dto import VolumeResponseDto
from .raw_client import AsyncRawBlockStorageClient, RawBlockStorageClient
from .types.list_block_storage_response import ListBlockStorageResponse
from .types.list_snapshots_block_storage_response import ListSnapshotsBlockStorageResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BlockStorageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBlockStorageClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBlockStorageClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBlockStorageClient
        """
        return self._raw_client

    def list_block_storage(
        self,
        *,
        vm_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBlockStorageResponse:
        """
        Returns block storage volumes for the authenticated account. Optionally filter by virtual machine.

        Parameters
        ----------
        vm_id : typing.Optional[str]
            Filter volumes attached to a specific virtual machine

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBlockStorageResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.list_block_storage()
        """
        _response = self._raw_client.list_block_storage(
            vm_id=vm_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeResponseDto:
        """
        Creates a new block storage volume. To preview pricing without creating anything, use POST /storage/block-storage/cost-estimate.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeResponseDto
            Volume created successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.create_block_storage(
            name="my-block-storage",
            size_gb=100,
            region="us-west-0",
        )
        """
        _response = self._raw_client.create_block_storage(
            name=name, size_gb=size_gb, region=region, request_options=request_options
        )
        return _response.data

    def get_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeResponseDto:
        """
        Returns details of a specific block storage volume

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeResponseDto
            Volume details

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.get_block_storage(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.get_block_storage(id, request_options=request_options)
        return _response.data

    def delete_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeDeletionResponseDto:
        """
        Deletes a block storage volume. This operation cannot be undone.

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeDeletionResponseDto
            Volume deletion initiated successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.delete_block_storage(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.delete_block_storage(id, request_options=request_options)
        return _response.data

    def get_cost_estimate_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CostEstimateResponseDto:
        """
        Returns the estimated cost for a volume with the given specs without creating it. Accepts the same body as create.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CostEstimateResponseDto
            Cost estimate for the volume

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.get_cost_estimate_block_storage(
            name="my-block-storage",
            size_gb=100,
            region="us-west-0",
        )
        """
        _response = self._raw_client.get_cost_estimate_block_storage(
            name=name, size_gb=size_gb, region=region, request_options=request_options
        )
        return _response.data

    def attach_block_storage(
        self, id: str, *, vm_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeOperationResponseDto:
        """
        Attaches a volume to a specified virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        vm_id : str
            The ID of the virtual machine to attach the volume to

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeOperationResponseDto
            Volume attachment initiated successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.attach_block_storage(
            id="123e4567-e89b-12d3-a456-426614174000",
            vm_id="f8d7e91c-f24d-4c21-b75e-4c7c5389c305",
        )
        """
        _response = self._raw_client.attach_block_storage(id, vm_id=vm_id, request_options=request_options)
        return _response.data

    def detach_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeOperationResponseDto:
        """
        Detaches a volume from its currently attached virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeOperationResponseDto
            Volume detachment initiated successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.detach_block_storage(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.detach_block_storage(id, request_options=request_options)
        return _response.data

    def resize_block_storage(
        self, id: str, *, size_gb: int, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeOperationResponseDto:
        """
        Increases the size of a block storage volume. The new size must be larger than the current size.

        Parameters
        ----------
        id : str
            Volume ID

        size_gb : int
            The new size of the volume in GB. Must be larger than the current size.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeOperationResponseDto
            Volume resize initiated successfully

        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.resize_block_storage(
            id="123e4567-e89b-12d3-a456-426614174000",
            size_gb=200,
        )
        """
        _response = self._raw_client.resize_block_storage(id, size_gb=size_gb, request_options=request_options)
        return _response.data

    def list_snapshots_block_storage(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSnapshotsBlockStorageResponse:
        """
        Returns all snapshots for the specified volume.

        Parameters
        ----------
        id : str
            Volume ID

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSnapshotsBlockStorageResponse


        Examples
        --------
        from americancloud import AmericancloudApi

        client = AmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.block_storage.list_snapshots_block_storage(
            id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._raw_client.list_snapshots_block_storage(
            id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data


class AsyncBlockStorageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBlockStorageClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBlockStorageClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBlockStorageClient
        """
        return self._raw_client

    async def list_block_storage(
        self,
        *,
        vm_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBlockStorageResponse:
        """
        Returns block storage volumes for the authenticated account. Optionally filter by virtual machine.

        Parameters
        ----------
        vm_id : typing.Optional[str]
            Filter volumes attached to a specific virtual machine

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBlockStorageResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.list_block_storage()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_block_storage(
            vm_id=vm_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeResponseDto:
        """
        Creates a new block storage volume. To preview pricing without creating anything, use POST /storage/block-storage/cost-estimate.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeResponseDto
            Volume created successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.create_block_storage(
                name="my-block-storage",
                size_gb=100,
                region="us-west-0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_block_storage(
            name=name, size_gb=size_gb, region=region, request_options=request_options
        )
        return _response.data

    async def get_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeResponseDto:
        """
        Returns details of a specific block storage volume

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeResponseDto
            Volume details

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.get_block_storage(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_block_storage(id, request_options=request_options)
        return _response.data

    async def delete_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeDeletionResponseDto:
        """
        Deletes a block storage volume. This operation cannot be undone.

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeDeletionResponseDto
            Volume deletion initiated successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.delete_block_storage(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_block_storage(id, request_options=request_options)
        return _response.data

    async def get_cost_estimate_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CostEstimateResponseDto:
        """
        Returns the estimated cost for a volume with the given specs without creating it. Accepts the same body as create.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CostEstimateResponseDto
            Cost estimate for the volume

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.get_cost_estimate_block_storage(
                name="my-block-storage",
                size_gb=100,
                region="us-west-0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cost_estimate_block_storage(
            name=name, size_gb=size_gb, region=region, request_options=request_options
        )
        return _response.data

    async def attach_block_storage(
        self, id: str, *, vm_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeOperationResponseDto:
        """
        Attaches a volume to a specified virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        vm_id : str
            The ID of the virtual machine to attach the volume to

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeOperationResponseDto
            Volume attachment initiated successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.attach_block_storage(
                id="123e4567-e89b-12d3-a456-426614174000",
                vm_id="f8d7e91c-f24d-4c21-b75e-4c7c5389c305",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.attach_block_storage(id, vm_id=vm_id, request_options=request_options)
        return _response.data

    async def detach_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeOperationResponseDto:
        """
        Detaches a volume from its currently attached virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeOperationResponseDto
            Volume detachment initiated successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.detach_block_storage(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.detach_block_storage(id, request_options=request_options)
        return _response.data

    async def resize_block_storage(
        self, id: str, *, size_gb: int, request_options: typing.Optional[RequestOptions] = None
    ) -> VolumeOperationResponseDto:
        """
        Increases the size of a block storage volume. The new size must be larger than the current size.

        Parameters
        ----------
        id : str
            Volume ID

        size_gb : int
            The new size of the volume in GB. Must be larger than the current size.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumeOperationResponseDto
            Volume resize initiated successfully

        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.resize_block_storage(
                id="123e4567-e89b-12d3-a456-426614174000",
                size_gb=200,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resize_block_storage(id, size_gb=size_gb, request_options=request_options)
        return _response.data

    async def list_snapshots_block_storage(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSnapshotsBlockStorageResponse:
        """
        Returns all snapshots for the specified volume.

        Parameters
        ----------
        id : str
            Volume ID

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSnapshotsBlockStorageResponse


        Examples
        --------
        import asyncio

        from americancloud import AsyncAmericancloudApi

        client = AsyncAmericancloudApi(
            api_client_secret="YOUR_API_CLIENT_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.block_storage.list_snapshots_block_storage(
                id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_snapshots_block_storage(
            id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data
