# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.api_error_dto import ApiErrorDto
from ..types.cost_estimate_response_dto import CostEstimateResponseDto
from ..types.volume_deletion_response_dto import VolumeDeletionResponseDto
from ..types.volume_operation_response_dto import VolumeOperationResponseDto
from ..types.volume_response_dto import VolumeResponseDto
from .types.list_block_storage_response import ListBlockStorageResponse
from .types.list_snapshots_block_storage_response import ListSnapshotsBlockStorageResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawBlockStorageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_block_storage(
        self,
        *,
        vm_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListBlockStorageResponse]:
        """
        Returns block storage volumes for the authenticated account. Optionally filter by virtual machine.

        Parameters
        ----------
        vm_id : typing.Optional[str]
            Filter volumes attached to a specific virtual machine

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListBlockStorageResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/storage/block-storage",
            method="GET",
            params={
                "vmId": vm_id,
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListBlockStorageResponse,
                    parse_obj_as(
                        type_=ListBlockStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VolumeResponseDto]:
        """
        Creates a new block storage volume. To preview pricing without creating anything, use POST /storage/block-storage/cost-estimate.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VolumeResponseDto]
            Volume created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/storage/block-storage",
            method="POST",
            json={
                "name": name,
                "sizeGb": size_gb,
                "region": region,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeResponseDto,
                    parse_obj_as(
                        type_=VolumeResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VolumeResponseDto]:
        """
        Returns details of a specific block storage volume

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VolumeResponseDto]
            Volume details
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeResponseDto,
                    parse_obj_as(
                        type_=VolumeResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VolumeDeletionResponseDto]:
        """
        Deletes a block storage volume. This operation cannot be undone.

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VolumeDeletionResponseDto]
            Volume deletion initiated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeDeletionResponseDto,
                    parse_obj_as(
                        type_=VolumeDeletionResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_cost_estimate_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CostEstimateResponseDto]:
        """
        Returns the estimated cost for a volume with the given specs without creating it. Accepts the same body as create.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CostEstimateResponseDto]
            Cost estimate for the volume
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/storage/block-storage/cost-estimate",
            method="POST",
            json={
                "name": name,
                "sizeGb": size_gb,
                "region": region,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CostEstimateResponseDto,
                    parse_obj_as(
                        type_=CostEstimateResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def attach_block_storage(
        self, id: str, *, vm_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VolumeOperationResponseDto]:
        """
        Attaches a volume to a specified virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        vm_id : str
            The ID of the virtual machine to attach the volume to

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VolumeOperationResponseDto]
            Volume attachment initiated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/attach",
            method="POST",
            json={
                "vmId": vm_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeOperationResponseDto,
                    parse_obj_as(
                        type_=VolumeOperationResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def detach_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VolumeOperationResponseDto]:
        """
        Detaches a volume from its currently attached virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VolumeOperationResponseDto]
            Volume detachment initiated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/detach",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeOperationResponseDto,
                    parse_obj_as(
                        type_=VolumeOperationResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def resize_block_storage(
        self, id: str, *, size_gb: int, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[VolumeOperationResponseDto]:
        """
        Increases the size of a block storage volume. The new size must be larger than the current size.

        Parameters
        ----------
        id : str
            Volume ID

        size_gb : int
            The new size of the volume in GB. Must be larger than the current size.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[VolumeOperationResponseDto]
            Volume resize initiated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/resize",
            method="PUT",
            json={
                "sizeGb": size_gb,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeOperationResponseDto,
                    parse_obj_as(
                        type_=VolumeOperationResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_snapshots_block_storage(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListSnapshotsBlockStorageResponse]:
        """
        Returns all snapshots for the specified volume.

        Parameters
        ----------
        id : str
            Volume ID

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListSnapshotsBlockStorageResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/snapshots",
            method="GET",
            params={
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListSnapshotsBlockStorageResponse,
                    parse_obj_as(
                        type_=ListSnapshotsBlockStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawBlockStorageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_block_storage(
        self,
        *,
        vm_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListBlockStorageResponse]:
        """
        Returns block storage volumes for the authenticated account. Optionally filter by virtual machine.

        Parameters
        ----------
        vm_id : typing.Optional[str]
            Filter volumes attached to a specific virtual machine

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListBlockStorageResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/storage/block-storage",
            method="GET",
            params={
                "vmId": vm_id,
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListBlockStorageResponse,
                    parse_obj_as(
                        type_=ListBlockStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VolumeResponseDto]:
        """
        Creates a new block storage volume. To preview pricing without creating anything, use POST /storage/block-storage/cost-estimate.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VolumeResponseDto]
            Volume created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/storage/block-storage",
            method="POST",
            json={
                "name": name,
                "sizeGb": size_gb,
                "region": region,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeResponseDto,
                    parse_obj_as(
                        type_=VolumeResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VolumeResponseDto]:
        """
        Returns details of a specific block storage volume

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VolumeResponseDto]
            Volume details
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeResponseDto,
                    parse_obj_as(
                        type_=VolumeResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VolumeDeletionResponseDto]:
        """
        Deletes a block storage volume. This operation cannot be undone.

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VolumeDeletionResponseDto]
            Volume deletion initiated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeDeletionResponseDto,
                    parse_obj_as(
                        type_=VolumeDeletionResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_cost_estimate_block_storage(
        self, *, name: str, size_gb: int, region: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CostEstimateResponseDto]:
        """
        Returns the estimated cost for a volume with the given specs without creating it. Accepts the same body as create.

        Parameters
        ----------
        name : str
            The name of the volume

        size_gb : int
            The size of the volume in GB

        region : str
            Label of the region where the volume will be created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CostEstimateResponseDto]
            Cost estimate for the volume
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/storage/block-storage/cost-estimate",
            method="POST",
            json={
                "name": name,
                "sizeGb": size_gb,
                "region": region,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CostEstimateResponseDto,
                    parse_obj_as(
                        type_=CostEstimateResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def attach_block_storage(
        self, id: str, *, vm_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VolumeOperationResponseDto]:
        """
        Attaches a volume to a specified virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        vm_id : str
            The ID of the virtual machine to attach the volume to

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VolumeOperationResponseDto]
            Volume attachment initiated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/attach",
            method="POST",
            json={
                "vmId": vm_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeOperationResponseDto,
                    parse_obj_as(
                        type_=VolumeOperationResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def detach_block_storage(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VolumeOperationResponseDto]:
        """
        Detaches a volume from its currently attached virtual machine

        Parameters
        ----------
        id : str
            Volume ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VolumeOperationResponseDto]
            Volume detachment initiated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/detach",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeOperationResponseDto,
                    parse_obj_as(
                        type_=VolumeOperationResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def resize_block_storage(
        self, id: str, *, size_gb: int, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[VolumeOperationResponseDto]:
        """
        Increases the size of a block storage volume. The new size must be larger than the current size.

        Parameters
        ----------
        id : str
            Volume ID

        size_gb : int
            The new size of the volume in GB. Must be larger than the current size.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[VolumeOperationResponseDto]
            Volume resize initiated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/resize",
            method="PUT",
            json={
                "sizeGb": size_gb,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    VolumeOperationResponseDto,
                    parse_obj_as(
                        type_=VolumeOperationResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_snapshots_block_storage(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListSnapshotsBlockStorageResponse]:
        """
        Returns all snapshots for the specified volume.

        Parameters
        ----------
        id : str
            Volume ID

        page : typing.Optional[int]
            Page number, 1-indexed. Defaults to 1 when omitted.

        page_size : typing.Optional[int]
            Items per page. Defaults to 100 when omitted; server cap 500.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListSnapshotsBlockStorageResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/storage/block-storage/{encode_path_param(id)}/snapshots",
            method="GET",
            params={
                "page": page,
                "pageSize": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListSnapshotsBlockStorageResponse,
                    parse_obj_as(
                        type_=ListSnapshotsBlockStorageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ApiErrorDto,
                        parse_obj_as(
                            type_=ApiErrorDto,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
